#!/usr/bin/env node

const { EOL } = require('os');

const { calculate } = require('./src/index.js');

process.stdin.on('data', data => {
  const lines = data.toString().split(EOL);

  lines.forEach(line => {
    const result = calculate(line);

    if (result != null) {
      if (process.env.DEBUG === 'true') {
        console.log(`${line} = ${result}`);
      } else {
        process.stdout.write(`${result}${EOL}`);
      }
    }
  });
});
